### PR TITLE
refact: Refactoring of set the game mode

### PR DESCRIPTION
**Pull request by ChugunovRoman**
I hope this look like as some refactoring of code :upside_down_face:

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
You should discuss before such changes!
The plan is to remove these variables completely, so changes in this pull request are, sadly but, just a waste of time.

**Comment by ChugunovRoman** [comment]
> You should discuss before such changes! The plan is to remove these variables completely, so changes in this pull request are, sadly but, just a waste of time.

Then how to determinant of the game mode? What the plan?

**Comment by Xottab-DUTY** [comment]
> > You should discuss before such changes! The plan is to remove these variables completely, so changes in this pull request are, sadly but, just a waste of time.
> 
> Then how to determinant of the game mode? What the plan?

There will be no game mode overall in the engine, the will be enabled/disabled features.  Ideally, these features willl be automatically enabled/disabled without the need to enable them in openxray.ltx. Game mode will be only checked in xrEngine/main.cpp (or moved to a new file)

**Comment by ChugunovRoman** [comment]
> > > You should discuss before such changes! The plan is to remove these variables completely, so changes in this pull request are, sadly but, just a waste of time.
> > 
> > 
> > Then how to determinant of the game mode? What the plan?
> 
> There will be no game mode overall in the engine, the will be enabled/disabled features. Ideally, these features willl be automatically enabled/disabled without the need to enable them in openxray.ltx. Game mode will be only checked in xrEngine/main.cpp (or moved to a new file)

I still don't have a good idea of what it will look like...

**Comment by ChugunovRoman** [comment]
So, Do I close the PR?

**Comment by Xottab-DUTY** [comment]
Yea 
image

**Comment by ChugunovRoman** [comment]
> > > You should discuss before such changes! The plan is to remove these variables completely, so changes in this pull request are, sadly but, just a waste of time.
> > 
> > 
> > Then how to determinant of the game mode? What the plan?
> 
> There will be no game mode overall in the engine, the will be enabled/disabled features. Ideally, these features willl be automatically enabled/disabled without the need to enable them in openxray.ltx. Game mode will be only checked in xrEngine/main.cpp (or moved to a new file)

Do you mean enable/disable features through the defines? And what does openxray.ltx have to do with it?

**Pull request closed without merging**
