### PR TITLE
Lower required GL version to 3.3 + extension

### PR DESCRIPTION
**Pull request by 375gnu**
just an experiment. instead of `GL_ARB_gpu_shader5` `GL_ARB_texture_gather` must be used as in https://github.com/dolphin-emu/dolphin/pull/1259/files.

potentially it's possible, so if there is an interest i can complete this pr

### CODE REVIEW

**Comment by vTurbine** [comment]
IMO the `GL_ARB_texture_gather` is useless because of, at least, these reasons:
-  `textureGather` returns only the first swizzle component of texels and particular channel specification is available only in GLSL 4;
- functions from the extension doesn't work with multisampled textures and MSAA will be completely broken;
-  the workaround in the PR you mentioned will cause to significant performance drop and, again, doesn't take MSAA into account.

I think it's ok to go with `GL_ARB_gpu_shader5`. But in this case you don't need to change shaders code because the extension already have support for implicit cast between int<->uint.

**Comment by 375gnu** [comment]
But if `GL_ARB_gpu_shader5` is supported then, unless a user has outdated drivers, GL4.1 is supported too. The only case i'm aware of when hardware supports GL_ARB_gpu_shader5 but not GL4.1 is AMD HDXXXX series (with exception of HD58xx and HD69xx) because they don't have almost unused in gamed fp64 support. But recent Mesa versions provide for those cards emulated fp64 so they expose GL4.5. And even with older Mesas it's possible to use MESA_GL_VERSION_OVERRIDE.

So if you want GL renderer for older hardware unable to support `GL_ARB_gpu_shader5` or maybe even `GL_ARB_gpu_shader4` then it might be worth to provide GL3.x and disable MSAA (anyway those cards are not powerful enough), on the other hand, GL4.1 capable hardware is as old as CoP, so only a few users still have so outdated hw.

**Comment by Xottab-DUTY** [comment]
It's a good idea to lower the minimum required OpenGL version. It would be excellent, if it can be solved with minimum drawbacks: disabled MSAA is OK, but decreased performance is bad and we need to try to minimize impact on performance.

**Comment by Xottab-DUTY** [comment]
The topmost priority is implementing cross-compilation from the original HLSL shaders. (#258)
We must direct all our efforts in this direction, rather than supporting special GLSL shaders.

**Pull request closed without merging**
