### PR TITLE
Add customizable framerate cap (closes #1349)

### LINKED ISSUE #1349: Add command to customize menu framerate cap
Add something like `g_menu_fps_limit` for users with >60hz monitors.

### PR DESCRIPTION
**Pull request by yohjimane**
This solution is only approximate since updateDelta is an int.

### CODE REVIEW

**Comment by yohjimane** [comment]
Working on menu UI for this.

**Comment by yohjimane** [comment]
This feature is done, but needs doublechecking of Polish, Russian and German translations.

**Comment by vTurbine** [comment]
Imo we should have menu capped to 30 FPS in all cases. There is nothing to show there at full speed. UX also won't suffer

**Comment by yohjimane** [comment]
> Imo we should have menu capped to 30 FPS in all cases. There is nothing to show there at full speed. UX also won't suffer

The menu feels relatively sluggish when playing at high frame rate, attached is screenshot of game after opening menu. This doesn't negatively effect anything, and is also a feature found in many modern games.

image

**Review by Xottab-DUTY — APPROVED** [review]

**Comment by Xottab-DUTY** [comment]
There's an issue – we can't use `depend="runtime"` because engine just sets FPS limit to a minimal value, when clamping it:
CUITrackBar isn't initialized yet and contains value 0, this value gets clamped to 30 and `rs_fps_limit 30` immediately gets called, which is not suitable totally.

We need to fix initialization orders it seems.

This might be related with #1024.

**Pull request merged**
