### PR TITLE
decouple openssl

### PR DESCRIPTION
**Pull request by alexgdi**
decouple openssl and merge crypto into xrCore

### CODE REVIEW

**Comment by nitrocaster** [comment]
Merged. Thank you!

**Comment by alexgdi** [comment]
@nitrocaster :)

**Comment by Kaffeine** [comment]
@alexgdi Do you speak Russian? We have only english irc channel yet, but may be we have to add russian channel too? We definitely need to coordinate our efforts.

**Comment by alexgdi** [comment]
@Kaffeine, да я говорю по русски)

**Pull request merged**
