### PR TITLE
Update detail height when using vid_restart

### LINKED ISSUE #1290: r__detail_height does not update after vid_restart
**Describe the bug**
Using `r__detail_height` and then doing `vid_restart` does not change the height of grass. 

**To Reproduce**

1. Open console
2. set `r__detail_height` to 2 (changed from default value of 1)
3. run `vid_restart`

**Expected behavior**
Grass height should change when vid_restart is ran, like how r__detail_density works.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Latest commit from dev: c264b090ae4c12fea6bda90a409a54c48bcdcd8a

### PR DESCRIPTION
**Pull request by yohjimane**
To fix: https://github.com/OpenXRay/xray-16/issues/1290

Needs revision, this doesn't work on release build for some reason 😞

### CODE REVIEW

**Review by Xottab-DUTY — APPROVED** [review]

**Comment by Xottab-DUTY** [comment]
I just updated the code.

@yohjimane, could you test the release build? I suspect it wasn't working because floats can't be just compared using `==`.

**Comment by yohjimane** [comment]
Will go ahead and test now- thank you for fixing that!

**Comment by yohjimane** [comment]
This seems to work correctly now using release build @Xottab-DUTY

**Comment by Xottab-DUTY** [comment]
Thank you!

**Pull request merged**
