### PR TITLE
[Feature]: Support Ascii1457's screen space shaders

### LINKED ISSUE #1398: Support new shaders from Ascii1457, Kennshade, TheRealBeef, Anomaly Team
## ascii1457's screen space shaders
Major thanks to Ascii1457 for granting permission to adapt their work!
- Support and implementation complete
- [Has minor bug with Beef's NVGs which is also present in anomaly.](https://github.com/OpenXRay/xray-16/assets/11345783/ea7abd8f-27fe-477c-b9a9-7a9ac5e0f21c)

## kennshade's enhanced shaders
- Support and implementation complete
- [Possible issue with lods](https://github.com/OpenXRay/xray-16/assets/11345783/9abf5f1f-c1d6-4e76-b12c-8b7ee943a9f5)

### please enter the below settings via console if it's your first time loading the branch
```
cfg_load grading_default
r2_gloss_factor 0.001
r2_gloss_min 0.35
r2_sun_lumscale 3.0
r2_sun_lumscale_amb 1.0
r2_sun_lumscale_hemi 1.1
```

## TheRealBeef's night vision shaders
- Support complete
- Needs additional scripts, or engine edits to function properly
- use these console commands to test:
```
r__nightvision 1
shader_param_7 100, .5, 0, 0
shader_param_8 1.1, 5.1, 5.0, 10.0
```

## Anomaly Gas Mask shaders
- Support complete
- Engine edits partially complete; just equip a helmet and you should see the appropriate overlay for it's condition and raindrops depending on weather and if you're under a covered area. 
- Whether the helmet has a visor or the visor has reflections is hardcoded for now; all helmets have visor & reflections
- ~~Needs additional scripts, or engine edits to function properly~~
- use these console commands and wear a helmet to test:
```
r2_drops_control .5, 0, .5 // size, ??, speed
r2_mask_control 1, 0, 0, 0 // mask condition, ???, reflections enable, ???
```

### PR DESCRIPTION
**Pull request by yohjimane**
Credits: Ascii1457, LVutner, Anomaly Team

Bootable, but still WIP, needs additional engine code ported from anomaly

Features to verify:
- [x] Ambient occlusion
- [x] Screen space shadows
- [x] Screen space reflections
- [x] Water reflections
- [x] Rain puddles
- [x] Depth of field
- [x] Indirect Light
- [x] Additional shadow features
- [x] Interactive grass
- [x] Shadow fixes
- [x] Skybox debanding
- [x] Flora fixes and improvements
- [x] Fog
- [x] Volumetric sun ray fixes

### CODE REVIEW

**Comment by yohjimane** [comment]
All shaders are now loading properly (or at least not crashing!)

The only shader that does not work currently is the DoF shader. This depends on a script, which depends on some more functionality to be ported form anomaly (mainly, missing script callbacks)

As of now, this is feature complete and ready for review.

**Comment by CasualDev242** [comment]
I've tested this, works great for the most part. Two questions if you don't mind:
1) Are you sure Indirect Illumination is working? I've tried cranking up values (after deleting shader cache), and even enabling debug mode, and don't notice any difference.
2) Is interactive grass supposed to be functional yet, or require further implementation? The grass isn't moving upon collision.

**Comment by yohjimane** [comment]
Hey @CasualDev242 

1) I will need to test this further.

2) Interactive grass can be configured as such:
ssfx_grass_interactive = player collision enable (0-1), max collisions (0-15), max distance (0-5000), mutant collision enable (0-1)

e.g. some good default values
ssfx_grass_interactive = 1,15,3000,1

Edit: on further testing, i found enabling ssfx_grass_interactive while in-game can cause a hang. As a bandaid, the default values of ssfx_grass_interactive have changed to:
0,0,2000,1 -> 1,8,2000,1

**Comment by yohjimane** [comment]
Hey @CasualDev242, thanks for calling out IL - i checked by uncommenting `G_IL_DEBUG_MODE` in shaders, and didn't see any difference.

On anomaly, I did the same thing and also didn't see any difference, so maybe that debug mode doesn't work properly. I reached out to Ascii to ask how to validate indirect lighting, hopefully will hear back soon!

**Comment by yohjimane** [comment]
@CasualDev242 Hey, indirect lighting and dof are now working with the latest changes. Dof support is basic and not dynamic yet.

We are splitting up the gamedata and engine changes into separate merges to capture some new scope, and for easier review, so i will be closing this merge.

Superseded by both: https://github.com/OpenXRay/xray-16/pull/1406/ https://github.com/OpenXRay/xray-16/pull/1407/

**Pull request closed without merging**
