### PR TITLE
fix: check luabind submodule existing

### LINKED ISSUE #812: Build failed with submodules
After I cloned my fork of main repo via `git clone git@github.com:ChugunovRoman/xray-16.git --recurse-submodules`\
Build steps:
1. mkdir bin && cd bin
2. cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib
3. make -j8

And I got error:
<details>
<summary>Output</summary>
<pre>
In file included from /home/ruut/Projects/otherProjects/xray-16/src/Common/Config.hpp:22,
                 from /home/ruut/Projects/otherProjects/xray-16/src/Common/Common.hpp:3,
                 from /home/ruut/Projects/otherProjects/xray-16/src/utils/xrMiscMath/pch.hpp:3,
                 from /home/ruut/Projects/otherProjects/xray-16/bin/src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/ruut/Projects/otherProjects/xray-16/Externals/submodule_check.hpp:4:2: error: #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.    Read the build instructions: https://github.com/OpenXRay/xray-16/wiki"
    4 | #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.\
      |  ^~~~~
In file included from /home/ruut/Projects/otherProjects/xray-16/src/Common/Config.hpp:22,
                 from /home/ruut/Projects/otherProjects/xray-16/src/Common/Common.hpp:3,
                 from /home/ruut/Projects/otherProjects/xray-16/Externals/cximage/ximacfg.h:7,
                 from /home/ruut/Projects/otherProjects/xray-16/Externals/cximage/ximacfg.cpp:1:
/home/ruut/Projects/otherProjects/xray-16/Externals/submodule_check.hpp:4:2: error: #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.    Read the build instructions: https://github.com/OpenXRay/xray-16/wiki"
    4 | #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.\
      |  ^~~~~
-- The C compiler identification is GNU 11.1.0
</pre>
</details>

<details>
<summary>ls -la Externals/luabind/luabind</summary>
<pre>
total 260
drwxr-xr-x 3 ruut ruut  4096 Jun  1 10:41 ./
drwxr-xr-x 7 ruut ruut  4096 Jun  1 10:41 ../
-rw-r--r-- 1 ruut ruut  3777 Jun  1 10:41 adopt_policy.hpp
-rw-r--r-- 1 ruut ruut  1500 Jun  1 10:41 back_reference_fwd.hpp
-rw-r--r-- 1 ruut ruut  3091 Jun  1 10:41 back_reference.hpp
-rw-r--r-- 1 ruut ruut 19346 Jun  1 10:41 class.hpp
-rw-r--r-- 1 ruut ruut  1676 Jun  1 10:41 class_info.hpp
-rw-r--r-- 1 ruut ruut  4770 Jun  1 10:41 config.hpp
-rw-r--r-- 1 ruut ruut  3696 Jun  1 10:41 container_policy.hpp
-rw-r--r-- 1 ruut ruut  1095 Jun  1 10:41 copy_policy.hpp
-rw-r--r-- 1 ruut ruut  3452 Jun  1 10:41 dependency_policy.hpp
drwxr-xr-x 3 ruut ruut  4096 Jun  1 10:41 detail/
-rw-r--r-- 1 ruut ruut  2046 Jun  1 10:41 discard_result_policy.hpp
-rw-r--r-- 1 ruut ruut  1765 Jun  1 10:41 error_callback_fun.hpp
-rw-r--r-- 1 ruut ruut  3242 Jun  1 10:41 error.hpp
-rw-r--r-- 1 ruut ruut  1639 Jun  1 10:41 exception_handler.hpp
-rw-r--r-- 1 ruut ruut  1499 Jun  1 10:41 from_stack.hpp
-rw-r--r-- 1 ruut ruut  1428 Jun  1 10:41 function.hpp
-rw-r--r-- 1 ruut ruut  1920 Jun  1 10:41 function_introspection.hpp
-rw-r--r-- 1 ruut ruut   523 Jun  1 10:41 get_main_thread.hpp
-rw-r--r-- 1 ruut ruut  3784 Jun  1 10:41 handle.hpp
-rw-r--r-- 1 ruut ruut  4720 Jun  1 10:41 iterator_policy.hpp
-rw-r--r-- 1 ruut ruut  1293 Jun  1 10:41 lua_argument_proxy.hpp
-rw-r--r-- 1 ruut ruut  1427 Jun  1 10:41 luabind.hpp
-rw-r--r-- 1 ruut ruut  1530 Jun  1 10:41 lua_extensions.hpp
-rw-r--r-- 1 ruut ruut  1335 Jun  1 10:41 lua_include.hpp
-rw-r--r-- 1 ruut ruut  3196 Jun  1 10:41 lua_index_proxy.hpp
-rw-r--r-- 1 ruut ruut  5481 Jun  1 10:41 lua_iterator_proxy.hpp
-rw-r--r-- 1 ruut ruut  1754 Jun  1 10:41 lua_proxy.hpp
-rw-r--r-- 1 ruut ruut  9180 Jun  1 10:41 lua_proxy_interface.hpp
-rw-r--r-- 1 ruut ruut  1359 Jun  1 10:41 lua_state_fwd.hpp
-rw-r--r-- 1 ruut ruut  3634 Jun  1 10:41 make_function.hpp
-rw-r--r-- 1 ruut ruut  4311 Jun  1 10:41 memory_allocator.hpp
-rw-r--r-- 1 ruut ruut  2358 Jun  1 10:41 memory.hpp
-rw-r--r-- 1 ruut ruut  1321 Jun  1 10:41 nil.hpp
-rw-r--r-- 1 ruut ruut   686 Jun  1 10:41 no_dependency.hpp
-rw-r--r-- 1 ruut ruut  1291 Jun  1 10:41 object.hpp
-rw-r--r-- 1 ruut ruut  1369 Jun  1 10:41 open.hpp
-rw-r--r-- 1 ruut ruut  7986 Jun  1 10:41 operator.hpp
-rw-r--r-- 1 ruut ruut  8041 Jun  1 10:41 out_value_policy.hpp
-rw-r--r-- 1 ruut ruut  3532 Jun  1 10:41 pointer_traits.hpp
-rw-r--r-- 1 ruut ruut  1266 Jun  1 10:41 prefix.hpp
-rw-r--r-- 1 ruut ruut  1919 Jun  1 10:41 raw_policy.hpp
-rw-r--r-- 1 ruut ruut  2391 Jun  1 10:41 return_reference_to_policy.hpp
-rw-r--r-- 1 ruut ruut  2578 Jun  1 10:41 scope.hpp
-rw-r--r-- 1 ruut ruut  1927 Jun  1 10:41 set_package_preload.hpp
-rw-r--r-- 1 ruut ruut  2082 Jun  1 10:41 shared_ptr_converter.hpp
-rw-r--r-- 1 ruut ruut   980 Jun  1 10:41 typeid.hpp
-rw-r--r-- 1 ruut ruut  1393 Jun  1 10:41 types.hpp
-rw-r--r-- 1 ruut ruut   514 Jun  1 10:41 version.hpp
-rw-r--r-- 1 ruut ruut  1742 Jun  1 10:41 weak_ref.hpp
-rw-r--r-- 1 ruut ruut  3639 Jun  1 10:41 wrapper_base.hpp
-rw-r--r-- 1 ruut ruut  1572 Jun  1 10:41 yield_policy.hpp
</pre>
</details>

All submodules was initialized. if commented `#include "submodule_check.hpp"` in `src/Common/Config.hpp` then code will compile successful. Maybe need to rewrite the condition for determining the presence of submodules?

uname -a:
```
Linux arch-linux 5.12.7-arch1-1 #1 SMP PREEMPT Wed, 26 May 2021 22:03:57 +0000 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by ChugunovRoman**
Close #812

### CODE REVIEW

**Comment by ChugunovRoman** [comment]
What's wrong with CI? :thinking:

**Comment by ChugunovRoman** [comment]
@Xottab-DUTY Hi, I made a new fix and just update include path in some projects. This fixed the issue with luabind check.

**Comment by Xottab-DUTY** [comment]
Please, just add it as a global include using `include_directories` to the main CMakelists.txt. This is how it should be fixed.

(I know that doing this is not recommended, but the Linux build system should follow our Windows build system way in this case)

**Comment by ChugunovRoman** [comment]
@Xottab-DUTY 

> Please, just add it as a global include using `include_directories` to the main CMakelists.txt. This is how it should be fixed.

Yes, this will be more correct decision.

> (I know that doing this is not recommended, but the Linux build system should follow our Windows build system way in this case)

What do you mean? Do I need to build the engine on windows firstly? I just don't work on windows, because this is very not convenient

**Comment by Xottab-DUTY** [comment]
No-no, I mean that on Windows luabind folder was already included globally for all projects, but it wasn't on Linux and you have fixed that :)

**Comment by ChugunovRoman** [comment]
> No-no, I mean that on Windows luabind folder was already included globally for all projects, but it wasn't on Linux and you have fixed that :)

Ahh, okay :)

**Comment by ChugunovRoman** [comment]
@Xottab-DUTY 
I noticed, that build for Linux x86 fails with error:
```
Error: pointer size mismatch in cross-build.
Try: make HOST_CC="gcc -m32" CROSS=...
```

Is it normal for this PR?

**Comment by Xottab-DUTY** [comment]
@Masterkatze, maybe, do you have any ideas?

**Comment by ChugunovRoman** [comment]
And also the window build in debug mode fails with error:
```
LINK : fatal error LNK1104: cannot open file 'd3dx9.lib' [D:\a\xray-16\xray-16\src\utils\ETools\ETools.vcxproj]
```

**Comment by Xottab-DUTY** [comment]
I will try to fix the Windows build today

**Comment by ChugunovRoman** [comment]
@Xottab-DUTY Is this PR able to approved?

**Comment by Xottab-DUTY** [comment]
Fix for Linux x86 build needed

**Comment by Masterkatze** [comment]
Linux x86 build should be fixed in https://github.com/OpenXRay/xray-16/pull/814

**Comment by Xottab-DUTY** [comment]
@ChugunovRoman, @Masterkatze, thank you!

**Pull request merged**
