### PR TITLE
Corrected precision control for x64 architecture on Windows

### PR DESCRIPTION
**Pull request by TarasHots**
Related to #219

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
One minor issue with this PR: we are using our own macros `XR_X64` and `XR_X86`. I think it would be better to use `XR_X64` instead of `_WIN64`. Please, correct me if I'm wrong.

**Comment by Xottab-DUTY** [comment]
@intorr can you say something about this?

**Comment by Xottab-DUTY** [comment]
@intorr can you say something about this?

**Comment by intorr** [comment]
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/control87-controlfp-control87-2

_MCW_PC (Precision control) not supported on ARM or x64 platforms.
_MCW_RC (Rounding control) supported on all platforms.

**Comment by Xottab-DUTY** [comment]
According to what @intorr said, we should only disable precion but not rounding:
```cpp
#ifndef XR_X64
     _controlfp(_PC_24, MCW_PC);
#endif
```

**Comment by TarasHots** [comment]
Thanks for quick feedback! I’ll make all changes as soon as possible

**Comment by Xottab-DUTY** [comment]
@TarasHots, also, try to do this with rebase or commit squash, so that this will be one-commit-PR

**Comment by TarasHots** [comment]
@Xottab-DUTY fixed notices and made it as one-commit PR

**Pull request merged**
