### PR TITLE
fix bugtrap include path.

### PR DESCRIPTION
**Pull request by fedan**

### CODE REVIEW

**Comment by nitrocaster** [comment]
You use old BugTrap version. It's still included in xray-16-libraries.zip, which I'm going to take care of. Check [bchavez/BugTrap](https://github.com/bchavez/BugTrap) for the latest version.

**Comment by fedan** [comment]
Ok.

**Comment by nitrocaster** [comment]
xray-16-libraries.zip now contains latest BugTrap snapshot with prebuilt binaries.

**Comment by fedan** [comment]
Please update URL to https://dl.dropboxusercontent.com/u/63973281/dev/xray/xray-16-libraries.zip

**Comment by fedan** [comment]
but everything figured https://dl.dropboxusercontent.com/u/63973281/dev/xray/xray-16-libraries.7z

**Comment by nitrocaster** [comment]
Ah, I forgot to rename zip after update. You can download it now.

**Comment by fedan** [comment]
Thanks.

**Pull request closed without merging**
