### PR TITLE
Fixed volumetric light of lamp.

### PR DESCRIPTION
**Pull request by qweasdd136963**
Fixed volumetric light of lamp.
Fixed calculation of the inverse matrix.

before:
https://streamable.com/rsow9

after:
https://streamable.com/k4zhr

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
@qweasdd136963, @SkyLoaderr, any ideas why and how volumetrics work correct in original Clear Sky engine? ([OXR CS](https://github.com/OpenXRay/xray-15) has this problem too)

Original Clear Sky:

**Comment by qweasdd136963** [comment]
https://github.com/OpenXRay/xray-16/commit/cc3644d64c294de03157b8ff453b13d37cfd2573

**Comment by Xottab-DUTY** [comment]
Ohh, thank you for that)

**Comment by qweasdd136963** [comment]
Armada replaced d3dxmatrixinverse with Fmatrix::invert. that's incorrect.

**Comment by ForserX** [comment]
Можешь к нам отправить? А то я в армейку уехал, а другим не др этого.

**Comment by qweasdd136963** [comment]
Это для oxr только. В окси нет такого бага: https://github.com/xrOxygen/xray-oxygen/blob/99ff23bb24ceecc9102f2b4904dd63637da29887/code/engine.vc2008/xrEngine/device.cpp#L226

**Comment by ForserX** [comment]
Сама реализация инверта матриц интересна и может быть полезна.

**Comment by LVutner** [comment]
Hey. How volumetric light looked before fix? 
streamable already deleted video.

**Comment by Xottab-DUTY** [comment]
@LVutner, if you can compile the engine, just replace `invert_44` back to `invert` and you will see the difference when you'll look at the lamp on the Lebedev's desk at Clear Sky base.

**Pull request merged**
