### PR TITLE
[Linux]: Crash in Garbage

### PR DESCRIPTION
**Pull request by sobkas**
Crash in Garbage after traveling from Dark Valey

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
Could you give me the save file with the crash?

**Comment by sobkas** [comment]
Change didn't work, need to look more closely

**Comment by sobkas** [comment]
[a259.sav.gz](https://github.com/OpenXRay/xray-16/files/12456560/a259.sav.gz)
Moving around, opening and closing PDA

**Comment by sobkas** [comment]
Still seeing problem:
#1  0x00007fffe55602d7 in cmp_pass<xr_fixed_map_node<SPass*, R_dsgraph::mapNormalItems>*> (left=@0x55556ede8868: 0x5555700748d8, 
    right=@0x55556ede87c8: 0x55557009df78) at ./src/Layers/xrRender/r__dsgraph_render.cpp:30
30	./src/Layers/xrRender/r__dsgraph_render.cpp: Nie ma takiego pliku ani katalogu.
(gdb) p left
$1 = (xr_fixed_map_node<SPass*, R_dsgraph::mapNormalItems> * const&) @0x55556ede8868: 0x5555700748d8
(gdb) p right
$2 = (xr_fixed_map_node<SPass*, R_dsgraph::mapNormalItems> * const&) @0x55556ede87c8: 0x55557009df78
(gdb) p right->first
$3 = (SPass *) 0x555561da33d0
(gdb) p left->first
$4 = (SPass *) 0x21

Something got corrupted?

**Comment by Xottab-DUTY** [comment]
> [a259.sav.gz](https://github.com/OpenXRay/xray-16/files/12456560/a259.sav.gz) Moving around, opening and closing PDA

Can't reproduce it on Windows

**Comment by sobkas** [comment]
353 entry in (SPass *) 0x21

> > [a259.sav.gz](https://github.com/OpenXRay/xray-16/files/12456560/a259.sav.gz) Moving around, opening and closing PDA
> 
> Can't reproduce it on Windows

It depends on what is in one past nrmPasses, if it's bad it crashes

**Comment by sobkas** [comment]
For now unable to reproduce, will open when possible.

**Comment by sobkas** [comment]
Was able to reproduce:
in file r__dsgraph_render.cpp line 51:
nrmPasses is populated from map
But for some reason on of items in nrmPasses have  nrmPasses[x]->first as nullptr, 
then in cmp_pass calls left->first->equal and because first is nullptr it crashes

**Comment by Xottab-DUTY** [comment]
> Was able to reproduce: in file r__dsgraph_render.cpp line 51: nrmPasses is populated from map But for some reason on of items in nrmPasses have nrmPasses[x]->first as nullptr, then in cmp_pass calls left->first->equal and because first is nullptr it crashes

May be @vTurbine knows something?

**Comment by sobkas** [comment]
> > Was able to reproduce: in file r__dsgraph_render.cpp line 51: nrmPasses is populated from map But for some reason on of items in nrmPasses have nrmPasses[x]->first as nullptr, then in cmp_pass calls left->first->equal and because first is nullptr it crashes
> 
> May be @vTurbine knows something?

Right now I'm thinking about not copying nullptr items in get_any_p something like

> for (value_type* cur = begin(); cur != _end; ++cur, ++_it)
        {
          if (!cur->first)
              D.resize(D.size - 1);
          else
              *_it = cur;
        }

**Comment by Xottab-DUTY** [comment]
> > > Was able to reproduce: in file r__dsgraph_render.cpp line 51: nrmPasses is populated from map But for some reason on of items in nrmPasses have nrmPasses[x]->first as nullptr, then in cmp_pass calls left->first->equal and because first is nullptr it crashes
> > 
> > 
> > May be @vTurbine knows something?
> 
> Right now I'm thinking about not copying nullptr items in get_any_p something like
> 
> > for (value_type* cur = begin(); cur != _end; ++cur, ++_it)
> > {
> > if (!cur->first)
> > D.resize(D.size - 1);
> > else
> > *_it = cur;
> > }

This suppresses the problem, but doesn't fix it. :trollsad:
`first` should never be nullptr, so we need to figure out why it's nullptr

**Comment by sobkas** [comment]
Ok, have generated core file https://drive.google.com/file/d/1WQY8PW0QiAec3u-9afdsDo_eofcwzFo8/view?usp=sharing

**Comment by sobkas** [comment]
It looks like it reads past the end of map/array

```(gdb) p map
$2 = (xr_fixed_map<SPass*, R_dsgraph::mapNormalItems, 2, xalloc<xr_fixed_map_node<SPass*, R_dsgraph::mapNormalItems> > > &) @0x7fffe572b728: {
  static SG_REALLOC_ADVANCE = <optimized out>, nodes = 0x55557c1480f0, pool = 200, limit = 256}
(gdb) p *0x55557c1480f0
$3 = 1679003728
(gdb) p map.nodes
$4 = (xr_fixed_map<SPass*, R_dsgraph::mapNormalItems, 2, xalloc<xr_fixed_map_node<SPass*, R_dsgraph::mapNormalItems> > >::value_type *) 0x55557c1480f0
(gdb) p map.nodes->first
$5 = (SPass *) 0x555564139050
(gdb) p map.nodes[0]->first
$6 = (SPass *) 0x555564139050
(gdb) p map.nodes[10]->first
$7 = (SPass *) 0x55556b067ea0
(gdb) p map.nodes[200]->first
$8 = (SPass *) 0x0
(gdb) p map.nodes[199]->first
$9 = (SPass *) 0x555560da9900
```

**Comment by sobkas** [comment]
I think problem is in
```map.get_any_p(nrmPasses);
            std::sort(nrmPasses.begin(), nrmPasses.end(), cmp_pass<mapNormal_T::value_type*>);```
get_any_p
map looks ok
but nrmPasses, there is something wrong with it, std::sort reads past its supposed end, so then it crashes because it have some garbage there.
Crash might depend on what kind of data is past nrmPasses end.

**Comment by Xottab-DUTY** [comment]
Do you use Clang or GCC to compile the engine?

**Comment by sobkas** [comment]
> Do you use Clang or GCC to compile the engine?

GCC 10.5.0-2 Debian Unstable

**Comment by sobkas** [comment]
So it reads from map it writes into vector and it's ok
```Map size 297, vector size 297 number of items written 297```
But then it sorts and it crashes on nrmPasses[x]-> first being nullptr
```
Thread 1 "Primary thread" received signal SIGSEGV, Segmentation fault.
SPass::equal (this=0x0, other=...) at ./src/xrCore/xr_resource.h:83
83	./src/xrCore/xr_resource.h: Nie ma takiego pliku ani katalogu.
```
But it reads past the end  of nrmPasses
```
gdb) p nrmPasses[296]->first
$634 = (SPass *) 0x555562b70790
(gdb) p nrmPasses[297]->first
$635 = (SPass *) 0x0
```
element nrmPasses[297] (starts with 0 so its 297+1, 298) shouldn't be sorted.
Even worse problem is that if garbage after nrmPasses causes nrmPasses[x]->first to be valid enough it doesn't stop there, it just going until it fails and crashes.

There must be some kind of memory corruption.

**Pull request closed without merging**
