### PR TITLE
Fixed crash if parent dialog holder is not set

### PR DESCRIPTION
**Pull request by ChugunovRoman**

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
Parent dialog holder always should be set! I don't think this fix should be here.

**Comment by ChugunovRoman** [comment]
> Parent dialog holder always should be set! I don't think this fix should be here.

Sometimes I got segmentation fault on this line, but I have not yet figured out the true reason.

**Comment by ChugunovRoman** [comment]
@Xottab-DUTY When I'll reproduce the bug I'll let you know

**Comment by ChugunovRoman** [comment]
Related #1031

**Pull request closed without merging**
