### PR TITLE
[Linux]: Fix crash while descending into X8

### LINKED ISSUE #1316: [Linux] - Stalker Clear Sky: I can't enter Agroprom Underground because of Segfault
**Describe the bug**
when I enter Agroprom Underground for the first time in the story (entering an excavated tunnel in the ground after fighting some Snorks climbing out of it) i get the loading screen for the next level but the game locks up, looking at the trace in GDB is a Segfault

**To Reproduce**
just enter the hole, there is a savegame created but amidst the loading screen it segfaults

**Expected behavior**
just like the other changes between levels before getting to Agroprom, don't segfault

**Screenshots**
nope

**BugTrap error report**

<details><summary>click for the GDB trace</summary><p>

```
@ typed this message inside the console before the bug
! Unknown command:  typed
@ now I'll advance into the hole
! Unknown command:  now
* Saving spawns...
* Saving objects...
* 20149 objects are successfully saved
* Game Biel Bestué de Luna - autosave.sav is successfully saved to file '\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Clear Sky\_appdata_\savedgames\biel bestué de luna - autosave.sav'
- Disconnect
- Destroying level
* [ D3D ]: textures[238628 K]
-cs 
* phase time: 0 ms
* phase cmem: 1554 K
* phase time: 163 ms
* phase cmem: 1554 K
* phase time: 0 ms
* phase cmem: 1554 K
* Loading spawn registry...
* 11404 spawn points are successfully loaded
* Loading objects...
* 20149 objects are successfully loaded
malloc(): invalid next size (unsorted)

Thread 1 "Primary thread" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: El fitxer o directori no existeix.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6e3c406 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6e2287c in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff6e235a4 in __libc_message (fmt=fmt@entry=0x7ffff6fb890f "%s\n") at ../sysdeps/posix/libc_fatal.c:150
#6  0x00007ffff6e9b147 in malloc_printerr (str=str@entry=0x7ffff6fbbc30 "malloc(): invalid next size (unsorted)") at ./malloc/malloc.c:5651
#7  0x00007ffff6e9e4bc in _int_malloc (av=av@entry=0x7ffff6ff6c80 <main_arena>, bytes=bytes@entry=88) at ./malloc/malloc.c:3991
#8  0x00007ffff6e9f48d in __GI___libc_malloc (bytes=88) at ./malloc/malloc.c:3305
#9  0x00007fffec23d135 in CGameGraph::set_current_level(unsigned int) () from /usr/local/lib/xrAICore.so
#10 0x00007fffec239d15 in AISpaceBase::Load(char const*) () from /usr/local/lib/xrAICore.so
#11 0x00007fffabaecb09 in CAI_Space::load(char const*) () from /usr/local/lib/xrGame.so
#12 0x00007fffabaf54da in CALifeGraphRegistry::setup_current_level() () from /usr/local/lib/xrGame.so
#13 0x00007fffabaf5af8 in CALifeGraphRegistry::update(CSE_ALifeDynamicObject*) () from /usr/local/lib/xrGame.so
#14 0x00007fffabb2170f in CALifeSimulatorBase::register_object(CSE_ALifeDynamicObject*, bool) () from /usr/local/lib/xrGame.so
#15 0x00007fffabb4efe8 in CALifeStorageManager::load(void*, unsigned int const&, char const*) () from /usr/local/lib/xrGame.so
#16 0x00007fffabb4f69c in CALifeStorageManager::load(char const*) () from /usr/local/lib/xrGame.so
#17 0x00007fffabb54659 in CALifeUpdateManager::load(char const*, bool, bool) () from /usr/local/lib/xrGame.so
#18 0x00007fffabb26c82 in CALifeSimulator::CALifeSimulator(IPureServer*, shared_str*) () from /usr/local/lib/xrGame.so
#19 0x00007fffabd871c2 in game_sv_Single::Create(shared_str&) () from /usr/local/lib/xrGame.so
#20 0x00007fffac27d7c8 in xrServer::Connect(shared_str&, GameDescriptionData&) () from /usr/local/lib/xrGame.so
#21 0x00007fffabe721d0 in CLevel::net_start2() () from /usr/local/lib/xrGame.so
#22 0x00007ffff7ce373d in CRenderDevice::BeforeFrame() () from /usr/local/lib/xrEngine.so
#23 0x00007ffff7ce4bb8 in CRenderDevice::ProcessFrame() () from /usr/local/lib/xrEngine.so
#24 0x00007ffff7ce56da in CRenderDevice::message_loop() () from /usr/local/lib/xrEngine.so
#25 0x00007ffff7ce59b7 in CRenderDevice::Run() () from /usr/local/lib/xrEngine.so
#26 0x00007ffff7cd4c3a in Startup() () from /usr/local/lib/xrEngine.so
#27 0x00007ffff7cd579b in RunApplication() () from /usr/local/lib/xrEngine.so
#28 0x00005555555558a6 in entry_point(char const*) ()
#29 0x00005555555555df in main ()
```

</p></details>

**Desktop (please complete the following information):**
 - OS: [Ubuntu 23.04]
 - OpenXRay build version [a5dce777b738c7368e745d65dfadfa7449305a11]
 - Sky Reclamation Project 1.1.4 [ba2100df9f4e108e554a5beeaa3d5f66d08f027a]

**Additional context**
using last commit to OpenXray
using Sky Reclamation Project 1.1.4 with last commit too without any optional mods just the widescreen patch

### LINKED ISSUE #1333: [Call of Pripyat] Game hangs when entering a location "lab X8"
**Describe the bug**
I'm not able to enter lab X8 on the latest version.
I'm receiving an error "malloc(): invalid next size (unsorted)" in the end.
Attaching the debug log from engine built with an option "-DCMAKE_BUILD_TYPE=Debug".

**To Reproduce**
1. Install the latest version on xray-16 (commit d44cd796f80fcc3993d2394a47f3e582f7c8a697).
2. Go to elevator and press F to enter lab X8
3. See game hangs

**Expected behavior**
Normally enter lab X8.

**Screenshots**
game hangs:
Screenshot from 2023-05-08 12-16-22

**BugTrap error report**
Debug log:
[xr_3da.log](https://github.com/OpenXRay/xray-16/files/11420213/xr_3da.log)
[user.ltx](https://github.com/OpenXRay/xray-16/files/11442941/user.ltx.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - OpenXRay build version d44cd796f80fcc3993d2394a47f3e582f7c8a697 (1.6.02_amd64)

Thanks in advance!

### PR DESCRIPTION
**Pull request by sobkas**
Standard +1 error, writing after the end of nodes array (fixes #1333)

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
But this is not an error, because we allocate `vertex_count + 1` nodes, and after the change one last node gets invalidated

**Comment by Xottab-DUTY** [comment]
~~Moreover, `convert_nodes` only gets called in Shadow of Chernobyl, so it's completely unrelated to #1333.~~

Oh, sorry, I forgot that it actually gets called in COP.

**Comment by sobkas** [comment]
> But this is not an error, because we allocate `vertex_count + 1` nodes, and after the change one last node gets invalidated

We allocate vertex_count + 1, but access essentially item vertex_count + 2.

Array counts from 0, so accessing nodes[vertex_count + 1] access item vertex_count + 2.
nodes[vertex_count] is accessing item vertex_count + 1 in array

**Comment by Xottab-DUTY** [comment]
Aaaaahhhhh, man, you're my saviour 😹

Thanks! That tricky bug got me...

**Comment by sobkas** [comment]
> Aaaaahhhhh, man, you're my saviour 😹
> 
> Thanks! That tricky bug got me...

You won't believe how many times I made same error or seen code that does the same.

**Pull request merged**
