### PR TITLE
ODE - asan detects underflow access with some saves.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
Can you give us savefiles to reproduce this?

**Comment by devnexen** [comment]
Unrelated issue but I was able to reproduce as well with this attached save file https://github.com/OpenXRay/xray-16/issues/362

**Comment by Xottab-DUTY** [comment]
So, what about save file?

**Comment by devnexen** [comment]
There is one in the link above.

**Comment by ForserX** [comment]
It's just not beautiful.

**Comment by eagleivg** [comment]
Thank you for drawing attention to the problem. The proposed method is not suitable, since inactive joints will be processed. Fixed in https://github.com/OpenXRay/xray-16/commit/08c82f06fc73f17918b8edcc7e6583080d06d14b

**Pull request closed without merging**
