### PR TITLE
LAN game launch segfaults on Linux, fix proposal.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
@devnexen, can you describe what are you tried to fix?

Now, with this _fix_, the game crashes on Windows when I'm trying to open servers list..

**Comment by devnexen** [comment]
What happens if you test getparent() in the condition ?

**Comment by Xottab-DUTY** [comment]
It's wrong to check against GetParent() since parent can be null

**Comment by collectioner** [comment]
@devnexen Relation between LAN and UI box is not clear. Also, we hadn't any issues related to the UI with MP on Windows. 

Agree with @Xottab-DUTY : can you describe the issue? Maybe we can fix it in other way.

**Comment by devnexen** [comment]
It simply segfault one accepting the LAN settings, it was just to give more infos about the cause.

**Pull request merged**
