### PR TITLE
Implementing ASAN for Debug

### PR DESCRIPTION
**Pull request by Giperion**
* EDIT: Removing deleting and changing const pointers in some places
* EDIT: Enable ASAN in Debug
* EDIT: Debug configuration using PURE_ALLOC for proper ASAN working
* WIP: Removing inline operator new and operator delete

### CODE REVIEW

**Comment by Giperion** [comment]
From 1018c2992204e9fbe981fad9cf7800939e35f1a2 Mon Sep 17 00:00:00 2001
From: Giperion <dereline@hotmail.com>
Date: Sat, 7 Aug 2021 02:27:08 +0300
Subject: [PATCH] * EDIT: Disable intensive memory check on debug. They too
 slow

---
 source/Client/BugTrap.cpp | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/source/Client/BugTrap.cpp b/source/Client/BugTrap.cpp
index 782df47..4f1eb95 100644
--- a/source/Client/BugTrap.cpp
+++ b/source/Client/BugTrap.cpp
@@ -538,8 +538,12 @@ BOOL WINAPI DllMain(HINSTANCE hModule, DWORD fdwReason, PVOID pvReserved)
 		CXmlReader::InitStdEntities();
 #endif
 		// Watch for memory leaks.
-		_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_CHECK_ALWAYS_DF | _CRTDBG_LEAK_CHECK_DF);
-		_CrtMemCheckpoint(&g_MemState);
+        //#GIPERION: Disable intensive memory check on debug. They too slow.
+        if (strstr(GetCommandLineA(), "-bugtrap_mem_check"))
+        {
+		    _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_CHECK_ALWAYS_DF | _CRTDBG_LEAK_CHECK_DF);
+		    _CrtMemCheckpoint(&g_MemState);
+        }
 #endif
 		g_hInstance = hModule;
 		AttachProcess();
-- 
2.28.0.windows.1

**Comment by Giperion** [comment]
BugTrap enables Debug CRT which makes the entire engine slow. Here's a patch to disable it:
```diff
From 1018c2992204e9fbe981fad9cf7800939e35f1a2 Mon Sep 17 00:00:00 2001
From: Giperion <dereline@hotmail.com>
Date: Sat, 7 Aug 2021 02:27:08 +0300
Subject: [PATCH] * EDIT: Disable intensive memory check on debug. They too
 slow

---
 source/Client/BugTrap.cpp | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/source/Client/BugTrap.cpp b/source/Client/BugTrap.cpp
index 782df47..4f1eb95 100644
--- a/source/Client/BugTrap.cpp
+++ b/source/Client/BugTrap.cpp
@@ -538,8 +538,12 @@ BOOL WINAPI DllMain(HINSTANCE hModule, DWORD fdwReason, PVOID pvReserved)
 		CXmlReader::InitStdEntities();
 #endif
 		// Watch for memory leaks.
-		_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_CHECK_ALWAYS_DF | _CRTDBG_LEAK_CHECK_DF);
-		_CrtMemCheckpoint(&g_MemState);
+        //#GIPERION: Disable intensive memory check on debug. They too slow.
+        if (strstr(GetCommandLineA(), "-bugtrap_mem_check"))
+        {
+		    _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_CHECK_ALWAYS_DF | _CRTDBG_LEAK_CHECK_DF);
+		    _CrtMemCheckpoint(&g_MemState);
+        }
 #endif
 		g_hInstance = hModule;
 		AttachProcess();
-- 
2.28.0.windows.1
```

**Review by Xottab-DUTY — APPROVED** [review]

**Comment by Xottab-DUTY** [comment]
@Masterkatze, could you review too?

**Comment by Xottab-DUTY** [comment]
Ура!

**Pull request merged**
