### PR TITLE
Added search of FreeImagePlus library and its include path

### PR DESCRIPTION
**Pull request by r-a-sattarov**

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
@eagleivg, @q4a, @Masterkatze, please look. All is ok?

**Comment by Masterkatze** [comment]
Is FreeImagePlus and FreeImage interchangeable or one depends on another? Shouldn't we also have `find_package(FreeImagePlus REQUIRED)` in that case?

Otherwise looks fine to me. Although I would use lowercase but that's another story :)

**Comment by Xottab-DUTY** [comment]
> Is FreeImagePlus and FreeImage interchangeable or one depends on another?

FreeImage is written in C and FreeImagePlus is C++ wrapper, so second depends on first.

> Shouldn't we also have find_package(FreeImagePlus REQUIRED) in that case?

I think it will be better, yes.

**Comment by Masterkatze** [comment]
> I think it will be better, yes.

I think it would be better to have separate `FindFreeImagePlus.cmake` file then.

**Review by Xottab-DUTY — APPROVED** [review]

**Comment by Xottab-DUTY** [comment]
Thank you!

**Pull request merged**
