### PR TITLE
Replace GLEW with GLAD

### PR DESCRIPTION
**Pull request by Xottab-DUTY**
Benefits:
* OpenGL 1.0 to 4.6
* OpenGL ES 1.0 to 3.2
  * Possibility to implement OpenGL ES support: https://github.com/OpenXRay/xray-16/issues/280#issuecomment-2136446760
* Handles function aliases
* One header file
* Carries no dependency (except for user provided function to load OpenGL extension. We use `SDL_GL_GetProcAddress`)
  * GLAD sources are integrated into our build system. This may be considered as disadvantage, but it gives us more portability.
  * Removes dependency from GLEW, which may be missing on some platforms (e.g. latest 32-bit Ubuntu versions)

The generated glad.h includes all available extensions, including `GL_ARB_separate_shader_objects`, but excluding `GL_EXT_separate_shader_objects` due to a conflict. I decided that it would be best to not include it at this moment (if ever).
Read more here: https://community.khronos.org/t/confused-gl-active-program-gl-current-program/65477.

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
@sobkas, @AMS21, please look at it! Does it work under Linux?

**Comment by AMS21** [comment]
> @sobkas, @AMS21, please look at it! Does it work under Linux?

Compiled with gcc 14.1.0 and seems to work fine on my machine :)

**Comment by alsed** [comment]
Hi @Xottab-DUTY  

I'm reading [here](https://bcmpinc.wordpress.com/2015/08/18/creating-an-opengl-4-5-context-using-sdl2-and-glad/)  that in order to have OpenGL functions available it's required to link them through `gladLoadGLLoader`

```
gladLoadGLLoader(SDL_GL_GetProcAddress);
// call OpenGl functions
```
I can not find `gladLoadGLLoader` in the generated glad.h, it's there a way to include it?

I suspect this can fix some inconsistent segfaults in `CreateDevice()` ~in #1761~

**Comment by Xottab-DUTY** [comment]
`gladLoadGLLoader` is an optional function and `SDL_GL_CreateContext` which crashes (according to the info in #1761) is unrelated to GLAD.

**Pull request merged**
