### PR TITLE
Close sleep dialog with ESC key

### PR DESCRIPTION
**Pull request by xobah**

### CODE REVIEW

**Comment by nitrocaster** [comment]
Please remove your last commit because our current development branch (ai_cleanup) already contains these updates.

**Comment by nitrocaster** [comment]
You reverted wrong commit. The last is "build tools" [6eef874](https://github.com/xobah/xray-16/commit/6eef874f62ec642092b9e5e8f47878a2166e791d). Instead of reverting, just reset to 7dce40d:
`git reset --hard 7dce40d`
After reset you can force push it to discard all following commits:
`git push -f`

**Comment by xobah** [comment]
I'm sorry, I not using git with a forks before

**Comment by xobah** [comment]
After pull request - all commits in my master-branch are sent to your branch?

**Comment by nitrocaster** [comment]
Exactly.

**Comment by xobah** [comment]
if I create a new branch - it too will go to your repo?

**Comment by nitrocaster** [comment]
If you create new branch, it will appear in your fork.
You've already opened this pull request, let's finish with it.

**Comment by xobah** [comment]
Thanks
Now, all ok?

**Comment by nitrocaster** [comment]
Almost OK - I removed redundant commits my myself. But anyway, thanks!

**Pull request merged**
