### PR TITLE
decouple openssl

### PR DESCRIPTION
**Pull request by alexgdi**
[Google Translate] openssl was decouple. crypto merged into xrCore. In xrCore proj was added the path to the static library openssl. All links to crypto have changed.

### CODE REVIEW

**Comment by nitrocaster** [comment]
Looks good, thank you! I'll merge this once I finish with script engine.

**Comment by alexgdi** [comment]
[Google Translate] I need a couple of edits links with mp_configs_verifer and mp screenshots_info. I will fixit as soon as.

**Comment by nitrocaster** [comment]
Please notify me once you done with the edits.

**Comment by alexgdi** [comment]
ok. it's done.

**Comment by nitrocaster** [comment]
I don't think it is done. Please check all crypto references and make sure xrGame, mp_screenshots_info and mp_configs_verifyer do compile.

**Comment by alexgdi** [comment]
del

**Comment by nitrocaster** [comment]
@alexgdi Are you going to fix your pull request?

**Comment by alexgdi** [comment]
Yes , I need more time to fix the linkage error.

**Pull request closed without merging**
